steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/ueabreu-backend:latest', '.']
  # El builder de Docker sube automáticamente al usar un tag de gcr.io

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'ueabreu-backend',
    '--image', 'gcr.io/${PROJECT_ID}/ueabreu-backend:latest',
    '--region', 'us-central1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--set-env-vars',
    "FRONTEND_URL1=https://ueabreu.com, \
     FRONTEND_URL2=https://www.ueabreu.com, \
     FRONTEND_URL3=http://localhost:5173, \
     BACKEND_URL=http://localhost:8080, \
     BACKEND_URL1=https://api.ueabreu.com, \
     SESION_SECRETKEY=SesionesUEABREU, \
     JWT_EXPIRES_IN=1h, \
     NODE_ENV=production, \
     DB_HOST=dpg-d4t0ncogjchc738fucr0-a.oregon-postgres.render.com, \
     DB_PORT=5432, \
     DB_USER=ueabreu, \
     DB_PASSWORD=Q2HusVQyaD4yyiSlUeXMyz5RjQFyFEYd, \
     DB_NAME=ueabreudb"
  ]

options:
  logging: CLOUD_LOGGING_ONLY
