steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/ueabreu-backend:latest', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'ueabreu-backend',
         '--image', 'gcr.io/${PROJECT_ID}/ueabreu-backend:latest',
         '--region', 'us-central1',
         '--platform', 'managed',
         '--allow-unauthenticated',
         '--set-env-vars', 'steps=valor_de_steps']

images:
- 'gcr.io/${PROJECT_ID}/ueabreu-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
